### ISSUE TITLE
Can I run this plugin against my custom DITA OT plugin?

### ISSUE THREAD

**Issue by ghost** [jason-fox/fox.jason.unit-test#3]
I was exploring the plugins functionality and I noticed that, plugin is running against some test suites. Is it possible to run the plugin against my custom DITA OT plugin like HTML and PDF?

**Comment by jason-fox** [comment]
Certainly - here is an example of a third-party plugin with a test [com.oxygenxml.editlink](https://github.com/jason-fox/com.oxygenxml.editlink). You just need a `test` folder with the tests and expectations. You could also reuse the GitHub Action if your plugin is public.

**Comment by ghost** [comment]
Thank you for sharing the details.
I am able to run the test within my html plugin. I have few clarification here.

- In which scenario the test is failing? I wanted to make my test fail ex: in my html codeblock is transformed to &lt;pre&gt; tag. How can I write a test case for fail scenario? 
- If some one extend my plugin and wrongly transforming codeblock to some other html tag, then I need to flag this in my unit test, is it possible?

**Comment by jason-fox** [comment]
This shows a canonically failed test  [here](https://github.com/jason-fox/fox.jason.unit-test/blob/master/test/failed-test/suite/test/failure/build.xml). More realistically, any ANT unit test that throws a `fail` will work. The usual way is to include a `compare-output` like [this](https://github.com/jason-fox/fox.jason.unit-test/blob/master/test/exec-html5/html-suite/test/p-block/build.xml#L10) .  The output must **exactly** match the [expectation.html](https://github.com/jason-fox/fox.jason.unit-test/blob/master/test/exec-html5/html-suite/test/p-block/expected.html) so in the case of a codeblock being returned as `<pre>` rather than `<pre><code>` the expectation will fail and the test will error.

Usually I generated my initial expectation for a test by running `ant -Dtest.copy=true` and then run the test suite for regression testing.
